version: 0.1
phases:
  install:
    commands:
      - apt-get update
      - apt-get install nodejs -y
      - gem install bundler
      - gem install middleman
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - middleman build
  post_build:
    commands:
      - aws s3 sync build/ "s3://${BUCKET_NAME}" --acl=public-read --delete
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /index.html /* /fonts/* /images/* /javascripts/* /stylesheets/* /favicon.ico
